add lccs reference in review 0.8.0 and set bdc with default schema
brazil-data-cube/bdc-catalog pull request #149
Opened 2021-03-08 18:29 UTC by betonr

- set BDC schema with default in creating new grid ref sys (close #148)
- add LCCS migration with dependence in revision 0.8.0

2021-03-08 18:34 UTC, fabianazioti approved these changes

2021-03-08 18:35 UTC, raphaelrpl requested changes

2021-03-08 18:35 UTC, raphaelrpl commented on bdc_catalog/models/grid_ref_sys.py
> +        db.metadata.schema = BDC_CATALOG_SCHEMA
Please review this line. The schema should not be set here. Try to set directly in the "Table" definition

2021-03-08 19:39 UTC, raphaelrpl approved these changes

2021-03-18 11:51 UTC, raphaelrpl approved these changes

2021-03-18 11:51 UTC, merged